title:              Search Engine Optimization Experts
brand:              expertengineoptimization
email:              your-email@example.com
description:        A search engine optimization blog from the experts.
author:             Cleverberry
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   cleverberry
github_username:    cleverberry
facebook_username:  cleverberry
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-minimal